openapi: 3.0.3
info:
  title: CSV REST API
  version: 1.0.0
  description: API for loading and querying CSV data files
servers:
  - url: http://localhost:8001
paths:
  /import:
    post:
      operationId: importCSV
      summary: Import a CSV file from a URL or upload
      description: |
        Import a CSV file by specifying either a URL query parameter
        or by providing the file name and uploading the CSV in the request body.
      parameters:
        - in: query
          name: url
          schema:
            type: string
            format: uri
          description: HTTP URL of the CSV file to import
        - in: query
          name: name
          schema:
            type: string
          description: Name of the CSV file when uploading directly
      requestBody:
        description: The CSV file content when uploading via `name` query parameter
        content:
          text/csv:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Successfully loaded CSV
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImportResponse"
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/{id}:
    get:
      operationId: fetchCSV
      summary: Query loaded CSV data
      description: Retrieve rows from a previously loaded CSV by UUID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: UUID of the loaded CSV resource
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
          description: Limit the number of rows returned
        - in: query
          name: sort
          schema:
            type: string
          description: Column name to sort ascending
        - in: query
          name: sort_desc
          schema:
            type: string
          description: Column name to sort descending
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
          description: Offset for pagination
        - in: query
          name: shape
          schema:
            type: string
            enum: [objects, array]
            default: "objects"
          description: Output JSON format `objects` for array of objects, `array` for array of arrays
        - in: query
          name: rowid
          schema:
            type: boolean
            default: true
          description: Show or hide the `rowid` field
      responses:
        "200":
          description: CSV data retrieved successfully
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ResponseObjects"
                  - $ref: "#/components/schemas/ResponseArray"
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    ImportResponse:
      type: object
      properties:
        ok:
          type: boolean
          example: true
        endpoint:
          type: string
          format: uri
          example: http://localhost:8001/api/123e4567-e89b-12d3-a456-426614174000
      required:
        - ok
        - endpoint
    ResponseBase:
      type: object
      properties:
        ok:
          type: boolean
          example: true
        query_ms:
          type: number
          format: double
          example: 2.681016922
        columns:
          type: array
          items:
            type: string
          example: ["rowid", "Mission", "Programme", "Consommation de CP"]
        total:
          type: integer
          example: 3

      required: [ok, query_ms, columns, total]
    ResponseObjects:
      allOf:
        - $ref: "#/components/schemas/ResponseBase"
        - type: object
          properties:
            rows:
              type: array
              items:
                type: object
                additionalProperties: true
    ResponseArray:
      allOf:
        - $ref: "#/components/schemas/ResponseBase"
        - type: object
          properties:
            rows:
              type: array
              items:
                type: array
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        error:
          type: string
        message:
          type: string
      required: [timestamp, error, message]
