// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FetchCSVParamsSortOrder.
const (
	ASC  FetchCSVParamsSortOrder = "ASC"
	DESC FetchCSVParamsSortOrder = "DESC"
)

// Defines values for FetchCSVParamsFormat.
const (
	Array   FetchCSVParamsFormat = "array"
	Objects FetchCSVParamsFormat = "objects"
)

// CSVResponse defines model for CSVResponse.
type CSVResponse struct {
	Columns []string      `json:"columns,omitempty"`
	Ok      bool          `json:"ok,omitempty"`
	QueryMs float64       `json:"query_ms,omitempty"`
	Rows    []interface{} `json:"rows,omitempty"`
	Total   int           `json:"total,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error     string    `json:"error"`
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`
}

// ImportResponse defines model for ImportResponse.
type ImportResponse struct {
	Endpoint string `json:"endpoint"`
	Ok       bool   `json:"ok"`
}

// FetchCSVParams defines parameters for FetchCSV.
type FetchCSVParams struct {
	// Limit Limit the number of rows returned
	Limit int `form:"limit,omitempty" json:"limit,omitempty"`

	// SortColumn Column name to sort by
	SortColumn string `form:"sortColumn,omitempty" json:"sortColumn,omitempty"`

	// SortOrder Sort order for sortColumn
	SortOrder FetchCSVParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`

	// Offset Offset for pagination
	Offset int `form:"offset,omitempty" json:"offset,omitempty"`

	// Format Output JSON format `objects` for array of objects, `array` for array of arrays
	Format FetchCSVParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// FetchCSVParamsSortOrder defines parameters for FetchCSV.
type FetchCSVParamsSortOrder string

// FetchCSVParamsFormat defines parameters for FetchCSV.
type FetchCSVParamsFormat string

// ImportCSVParams defines parameters for ImportCSV.
type ImportCSVParams struct {
	// Url HTTP URL of the CSV file to import
	Url string `form:"url,omitempty" json:"url,omitempty"`

	// Name Name of the CSV file when uploading directly
	Name string `form:"name,omitempty" json:"name,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Query loaded CSV data
	// (GET /api/{id})
	FetchCSV(ctx echo.Context, id openapi_types.UUID, params FetchCSVParams) error
	// Import a CSV file from a URL or upload
	// (POST /import)
	ImportCSV(ctx echo.Context, params ImportCSVParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// FetchCSV converts echo context to params.
func (w *ServerInterfaceWrapper) FetchCSV(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params FetchCSVParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "sortColumn" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortColumn", ctx.QueryParams(), &params.SortColumn)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sortColumn: %s", err))
	}

	// ------------- Optional query parameter "sortOrder" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortOrder", ctx.QueryParams(), &params.SortOrder)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sortOrder: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", ctx.QueryParams(), &params.Format)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FetchCSV(ctx, id, params)
	return err
}

// ImportCSV converts echo context to params.
func (w *ServerInterfaceWrapper) ImportCSV(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ImportCSVParams
	// ------------- Optional query parameter "url" -------------

	err = runtime.BindQueryParameter("form", true, false, "url", ctx.QueryParams(), &params.Url)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter url: %s", err))
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ImportCSV(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/:id", wrapper.FetchCSV)
	router.POST(baseURL+"/import", wrapper.ImportCSV)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RWwXLbNhD9FQzaoyxRsqMkvKVKOnUnjV3L9sXR1BC5lJAQALMA5Wg8+vfOLimJoqjU",
	"h3Z6kkgAu+8t3r7ls0ycKZwFG7yMn6VPlmAU/51M72/AF856oMcCXQEYNPBi4vLSWP4L35UpcpDxg0T3",
	"pFPZk39o77Wzsiev0S1QGQOyJyfOemeMCtpZkYKYXMtZT+oAhuOEdQEylj6gtgu56W1fKES1pmf39SBd",
	"wBJ2m+bO5aAsbftWAq7/MofYRv3xm2E0HL8djXoyc2hUkLFMXTnPCVodxZZmDkhB0D01Qe0wBBdUfhD5",
	"fHda2wALOr7H7uZfIAl08AOiw9P1BFrurIIB79UCuiukDfigTEGre1YqwBkt7YltjxAz+FZqhJTua3++",
	"VyPY55t1kLg0hcPwAxY2LZy24aBAchlCEQ8GuUtUvnQ+xG+iaDhQhR4MR+dw8Wr8+gzevJ2fDUfp+Zm6",
	"eDU+uxiNx8OL4euLKIpk475K1MecXiiMFnX3lThv8R6Tpf3aZo4ip+AT1AXpVsby3fWlyByK3KlU24VQ",
	"NhWsOXqYTO9FqoISmc7BE1gduAi0cPNheiveXV/KnlwB+ircsB/1I2ZRgFWFlrE870f9c9mThQpLrisX",
	"61mnG3pYQDgGdQMBNaxAkHBFhs4IJQqElXalz9cMFlKGN1+Lu7vL95IzInfjZSpj+SuEZDmZ3nNiVAYC",
	"oJfxQzsVHRYuE2EJzbAI3pWYkOg0bSPwsietMtwbZAv7+ldXVJnNgXbLknceybYN4qM2OjCEqmcJEFNH",
	"CCVaSLcw+Gb2OHI6J5upjbbalEbGw65GbuedsO8JiiaCE95hEPP1iWS0Wh04yPiP5KYU1WEKyEI7CHMq",
	"zxVtP0iTQqbKnIr6bjphsRPLB/n+Az/Sy9kLKn2VZR4CAynUQlsWzAkgjvd2lzd6SXmvylCUQfw+vfok",
	"Kk2Ix6oj/SNDYCOmy67f9sQjv2qt8h9/AmUttu5a1XEb9dq/qaZAR9FmpO3KFLlfR1FUDUkboHJDVRS5",
	"Trh2gy+euD430v+MkMlY/jTYD+NBPYkHzTHMrtQS5NZwsHaAVPgyScD7rMxznlk7cv8SosNRttkwKl8a",
	"o3AtY/knVbvpDASP/XegeX7w3HC+w8Wq+SIUHyMHJbPyBSQ6Y3cFHZaAQom7m4+V54qdVX22Dml7gW6l",
	"2ZjJHTgIdyvZdFlsTZvWKIm2/JecCXwQc5eu+5/tkTdWwF5gjr/d3l4zutogd0SCEzX7blGWmMtuR+ya",
	"eced84k4tpM+LcE2SKcaIQn5Kbvinx8Z1ayycPDhF5euW3oK8D0MEr861NGOxlxbxcnaQY8UfdtkUCdo",
	"M1lpJR4J72NbBvzx9l/1Yuv7pwP8tNF7jR74H9rwuJfqrwJWJ9bFrDh4wNVWzyTEE99scjPb/B0AAP//",
	"/UKGzTEMAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
