// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FetchCSVParamsShape.
const (
	Array   FetchCSVParamsShape = "array"
	Objects FetchCSVParamsShape = "objects"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error     string    `json:"error"`
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`
}

// ImportResponse defines model for ImportResponse.
type ImportResponse struct {
	Endpoint string `json:"endpoint"`
	Ok       bool   `json:"ok"`
}

// ResponseArray defines model for ResponseArray.
type ResponseArray struct {
	Columns []string        `json:"columns"`
	Ok      bool            `json:"ok"`
	QueryMs float64         `json:"query_ms"`
	Rows    [][]interface{} `json:"rows,omitempty"`
	Total   int             `json:"total"`
}

// ResponseBase defines model for ResponseBase.
type ResponseBase struct {
	Columns []string `json:"columns"`
	Ok      bool     `json:"ok"`
	QueryMs float64  `json:"query_ms"`
	Total   int      `json:"total"`
}

// ResponseObjects defines model for ResponseObjects.
type ResponseObjects struct {
	Columns []string                 `json:"columns"`
	Ok      bool                     `json:"ok"`
	QueryMs float64                  `json:"query_ms"`
	Rows    []map[string]interface{} `json:"rows,omitempty"`
	Total   int                      `json:"total"`
}

// FetchCSVParams defines parameters for FetchCSV.
type FetchCSVParams struct {
	// Size Limit the number of rows returned
	Size int `form:"size,omitempty" json:"size,omitempty"`

	// Sort Column name to sort ascending
	Sort string `form:"sort,omitempty" json:"sort,omitempty"`

	// SortDesc Column name to sort descending
	SortDesc string `form:"sort_desc,omitempty" json:"sort_desc,omitempty"`

	// Offset Offset for pagination
	Offset int `form:"offset,omitempty" json:"offset,omitempty"`

	// Shape Output JSON format `objects` for array of objects, `array` for array of arrays
	Shape FetchCSVParamsShape `form:"shape,omitempty" json:"shape,omitempty"`

	// Rowid Show or hide the `rowid` field
	Rowid bool `form:"rowid,omitempty" json:"rowid,omitempty"`
}

// FetchCSVParamsShape defines parameters for FetchCSV.
type FetchCSVParamsShape string

// ImportCSVParams defines parameters for ImportCSV.
type ImportCSVParams struct {
	// Url HTTP URL of the CSV file to import
	Url string `form:"url,omitempty" json:"url,omitempty"`

	// Name Name of the CSV file when uploading directly
	Name string `form:"name,omitempty" json:"name,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Query loaded CSV data
	// (GET /api/{id})
	FetchCSV(ctx echo.Context, id openapi_types.UUID, params FetchCSVParams) error
	// Import a CSV file from a URL or upload
	// (POST /import)
	ImportCSV(ctx echo.Context, params ImportCSVParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// FetchCSV converts echo context to params.
func (w *ServerInterfaceWrapper) FetchCSV(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params FetchCSVParams
	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", ctx.QueryParams(), &params.Size)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter size: %s", err))
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort: %s", err))
	}

	// ------------- Optional query parameter "sort_desc" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_desc", ctx.QueryParams(), &params.SortDesc)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort_desc: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "shape" -------------

	err = runtime.BindQueryParameter("form", true, false, "shape", ctx.QueryParams(), &params.Shape)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter shape: %s", err))
	}

	// ------------- Optional query parameter "rowid" -------------

	err = runtime.BindQueryParameter("form", true, false, "rowid", ctx.QueryParams(), &params.Rowid)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rowid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FetchCSV(ctx, id, params)
	return err
}

// ImportCSV converts echo context to params.
func (w *ServerInterfaceWrapper) ImportCSV(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ImportCSVParams
	// ------------- Optional query parameter "url" -------------

	err = runtime.BindQueryParameter("form", true, false, "url", ctx.QueryParams(), &params.Url)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter url: %s", err))
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ImportCSV(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/:id", wrapper.FetchCSV)
	router.POST(baseURL+"/import", wrapper.ImportCSV)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RXW3PbNhP9Kxh83yOtmx0l4VviplN30li1nLw4mggilhIS4hIAVKJ69N87u9SFoihf",
	"ptPpkyjics7unj0A73lmtbMGTAw8vechW4AW9PjOe+tvIDhrAuAL560DHxXQMOAwPsSVA57yEL0yc75O",
	"uIYQxBxax6LSEKLQDkdz67WIPOVSRDjDIZ40l6wT7uF7qTxInt7V1icbBnu8yW6xnX2FLCLelXbWxwei",
	"MNJZZSI9/xTaFbh+EaNLu93CZqJY2BDTV71evyuc6vYH53DxYvjyDF69np31B/L8TFy8GJ5dDIbD/kX/",
	"5UWv1+PJPrLSq+OYEm6/HQBGX8Ju1szaAoQ5Ct1+w5i3fNuC3Yb5xnuxQgBRFNc5T+/u+f895Dzl/+vu",
	"y93d1Lq7XfZWBODrpJkib3/Qr4qgQ62oglDWSeP/+ojYpEaNMI6qkNmi1CYc5OQOgZXkCf9DhaCs4Qkf",
	"eTv3QpNOLq0JVmsRlTVMArscYU6aJGvKa7B+UgkS/r0Ev/qiD7kNOsNX/V5/+HowqNVa2nJW1CRsSj0D",
	"T9g2iuJgh/PdLGUizHFaW7l36MkuR9vdHhLANb0J/54EhJQKEy+KUW3iQQ73rB7XB75UJre4tYSQeeVw",
	"d57yN6MrllvPCiukMnMmjGSUFPxzOf7EpIiC5aoAyoyK1L84cPNufMvejK54wpfgQ7Vdv9Pr9Kj6Doxw",
	"iqf8vNPvYMs6ERcUG/X5vZJr/DOHeEzqBqJXsASGeWG5t5oJ5jwslS1DsSKyIInebMU+frz6hROiJ7Fe",
	"SZ7yXyFmi8vxJwL2QkMEH6hMh1C4mNmcxQXUt/UQbOkzFJvCaUieJ9wITZLCrtlrqSpLVeoD2y1Lmnnk",
	"uE0S75VWkShUkkZCFLqHWHoDckuDKrPnEdRfyHCPrJVRutQ87bfJvwl7SYpnuBmLlgXrIxMhA4NKOAVp",
	"fTyAfDS4NhSc8SjMF5z1PKzrPA8QSdBOzJUhPZyAsDS3PX29p6TvuoyujOz38fUHVpWcTauWC1OiQA2J",
	"tdy8TdiUXjVG6SGcSsRCuMMaS8hFWcRdfwc6tZD1Xe1NZQaTJ4hvvLA/mPVsoSSQBqd0LkxZrqA4pbzt",
	"0dFC68RZO8GOqUyQXGDQ61Unk4lQXQ+Ec4XKqGTdrwG53df2twae4bNbg8ZwnzK/OtE3TtnQ79YE/caV",
	"JAtllkEIeVkUdNTtYn9GPA+xOrwZrtfEKpRaC7/iKf8Ta1F3K6RHxt9VdB2jC4ANLc5aXdeYoGXo6mig",
	"wUGmcnJ8UHEBngn28eZ9dQ6wnX1+NtbjdOftUtFhgWqhTai58ego3fYgwTEEUYYe0S0hRDazctX5bI78",
	"uiL2BMP+7fZ2ROw2pr0LJFq2ib5dsqUveLtLt10hj/vkA8bYBP2xAFMLWioPWSxWJyjQz0OGNqmOFQjx",
	"rZWrhp4i/IzdLCwPdbQLY6aMILDmpkeKvq1HsAFoRrJUgk2R77QpA77+h538kPIbnxMt5Me13qv1wH/Q",
	"hse9tLmpkDr9JplVDAH8cqtnFGLLJ9A5ftmsJ+u/AwAA//997+p4Mg4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
